const properties = [
  {
    attribute: "Techstack",
    list: [
      "C",
      "C++",
      "Go",
      "GraphQL",
      "Java",
      "Javascript",
      "jQuery",
      "Mongoose",
      "Nodejs",
      "NoSQL",
      "Perl",
      "PHP",
      "Python",
      "PostgreSQL",
      "Rails",
      "React",
      "Ruby",
      "SQL",
      "Swift"
    ]
  },
  { attribute: "Status", list: ["Ongoing", "Completed"] },
  { attribute: "Phase", list: ["Prototype", "Delivery"] },
  {
    attribute: "Region",
    list: [
      "Australia",
      "China",
      "Europe",
      "India",
      "North America",
      "Latin America",
      "Souteast Asia"
    ]
  },
  {
    attribute: "Office",
    list: []
  },
  {
    attribute: "Industry",
    list: [
      "Accounting",
      "Airlines/Aviation",
      "Alternative Dispute Resolution",
      "Alternative Medicine",
      "Animation",
      "Apparel & Fashion",
      "Architecture & Planning",
      "Arts & Crafts",
      "Automotive",
      "Aviation & Aerospace",
      "Banking",
      "Biotechnology",
      "Broadcast Media",
      "Building Materials",
      "Business Supplies & Equipment",
      "Capital Markets",
      "Chemicals",
      "Civic & Social Organization",
      "Civil Engineering",
      "Commercial Real Estate",
      "Computer & Network Security",
      "Computer Games",
      "Computer Hardware",
      "Computer Networking",
      "Computer Software",
      "Construction",
      "Consumer Electronics",
      "Consumer Goods",
      "Consumer Services",
      "Cosmetics",
      "Dairy",
      "Defense & Space",
      "Design",
      "Education Management",
      "E-learning",
      "Electrical & Electronic Manufacturing",
      "Entertainment",
      "Environmental Services",
      "Events Services",
      "Executive Office",
      "Facilities Services",
      "Farming",
      "Financial Services",
      "Fine Art",
      "Fishery",
      "Food & Beverages",
      "Food Production",
      "Fundraising",
      "Furniture",
      "Gambling & Casinos",
      "Glass, Ceramics & Concrete",
      "Government Administration",
      "Government Relations",
      "Graphic Design",
      "Health, Wellness & Fitness",
      "Higher Education",
      "Hospital & Health Care",
      "Hospitality",
      "Human Resources",
      "Import & Export",
      "Individual & Family Services",
      "Industrial Automation",
      "Information Services",
      "Information Technology & Services",
      "Insurance",
      "International Affairs",
      "International Trade & Development",
      "Internet",
      "Investment Banking/Venture",
      "Investment Management",
      "Judiciary",
      "Law Enforcement",
      "Law Practice",
      "Legal Services",
      "Legislative Office",
      "Leisure & Travel",
      "Libraries"
    ]
  }
];

module.exports = properties;
